let jobsData = [
  {
    id: null,
    image: '/mars.jpeg',
    name: 'Mars',
    date: '11:10:2195',
    pay: 50000000,
    isBooked: false,
    fluff: 'A barren planet with little resources after it was used up by mega capitalists.',
  },
  {
    id: null,
    image: '/jupiter.jpeg',
    name: 'Jupiter',
    date: '6:05:2198',
    pay: 10000000,
    isBooked: false,
    fluff: 'Its a big gas giant and you won\'t be able to land your rig on the surface.',
  },
  {
    id: null,
    image: '/pluto.jpeg',
    name: 'Pluto',
    date: '01:21:2234',
    pay: 100000000,
    isBooked: false,
    fluff: 'Be careful its too small to land on normally so you have to space parallel park.',
  },
  {
    id: null,
    image: '/lv426.png',
    name: 'LV-426',
    date: '04:22:2179',
    pay: 5000000,
    isBooked: false,
    fluff: 'Make sure to grab all ominous eggs in the ruins of a long dead alien species.',
  },
  {
    id: null,
    image: '/krypton.jpeg',
    name: 'Krypton',
    date: '06:03:2232',
    pay: 7500000,
    isBooked: false,
    fluff: 'Better get there quick before it blows up, lots of green rocks to collect.',
  },
  {
    id: null,
    image: '/proxima.jpeg',
    name: 'Alpha Centauri',
    date: '02:22:2379',
    pay: 1000000,
    isBooked: false,
    fluff: 'Its a long trip out there, maybe a few generations at least but that is what truckers do!',
  },
  {
    id: null,
    image: '/venus.jpg',
    name: 'Venus',
    date: '02:14:2087',
    pay: 10000,
    isBooked: false,
    fluff: 'Turns out the oceans are made of CapriSun, take a giant straw with you and get that.',
  },
  {
    id: null,
    image: '/moon.jpeg',
    name: 'Moon',
    date: '10:11:2192',
    pay: 5560000,
    isBooked: false,
    fluff: 'Our clones up on the moon have been acting up.  Go deliver a shipment of fresh clones.',
  },
];

module.exports = jobsData;
